### ISSUE TITLE
Bro why are you asking for our browsing history?

### ISSUE THREAD

**Issue by ltosh9802** [Presto412/CoursePage-Download-Manager#2]
The extension is asking for our browsing history man. That's why I've disabled it temporarily. Please fix the issue.

**Comment by Presto412** [comment]
With the latest update, I've fixed the multi-tab access error by refreshing the cookie(JSESSIONID) and reloading the page, which uses the chrome.tabs API. The tabs API used here gives a browser history warning.
[https://developer.chrome.com/extensions/permission_warnings](url)
I'll try doing a workaround though.

**Comment by ltosh9802** [comment]
Oh. Alrighty. 👍

**Comment by Presto412** [comment]
Issue has been fixed. Update should deploy in under 60 minutes.
